# Generated by Django 4.2.4 on 2023-10-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registros_usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=60)),
                ('correo_electronico', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
