# Generated by Django 4.2.4 on 2023-10-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros_usuarios',
            name='apellidos',
            field=models.CharField(max_length=60, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='registros_usuarios',
            name='correo_electronico',
            field=models.CharField(max_length=45, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='registros_usuarios',
            name='nombre',
            field=models.CharField(max_length=45, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='registros_usuarios',
            name='password',
            field=models.CharField(max_length=12, verbose_name='Contraseña'),
        ),
    ]
