# Generated by Django 4.2.4 on 2023-10-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='roles',
        ),
    ]
