# Generated by Django 4.2.4 on 2023-10-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_delete_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=20, verbose_name='Rol')),
            ],
        ),
    ]
