# Generated by Django 4.2.4 on 2023-10-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
            ],
        ),
    ]
