# Generated by Django 4.2.4 on 2023-10-24 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_carrito_producto_venta_itemcarrito_carrito_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoRealizado',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('imagen', models.ImageField(null=True, upload_to='images/', verbose_name='imagen')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('is_available', models.BooleanField(default=True, verbose_name='aviable')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.categoria', verbose_name='categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='id',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_carrito',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.carrito', verbose_name='carrito'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.carrito', verbose_name='carrito'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='pedidorealizado',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.carrito', verbose_name='productos'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='homepage.productos', verbose_name='producto'),
            preserve_default=False,
        ),
    ]
